import IISKursovaya_rabota_Tatarincev_BPC2001ПродуктыEController from '../i-i-s-kursovaya-rabota-tatarincev-b-p-c2001-продукты-e';

var IISKursovaya_rabota_Tatarincev_BPC2001ПродуктыENewController = IISKursovaya_rabota_Tatarincev_BPC2001ПродуктыEController;
export default IISKursovaya_rabota_Tatarincev_BPC2001ПродуктыENewController;
