//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_Tatarincev_BPC2001
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class3.
    /// </summary>
    [Caption("New class3")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass3E", new string[0])]
    [View("NewClass3L", new string[0])]
    public class NewClass3 : ICSSoft.STORMNET.DataObject
    {
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass3E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass3E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass3E", typeof(IIS.Kursovaya_rabota_Tatarincev_BPC2001.NewClass3));
                }
            }
            
            /// <summary>
            /// "NewClass3L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass3L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass3L", typeof(IIS.Kursovaya_rabota_Tatarincev_BPC2001.NewClass3));
                }
            }
        }
    }
}
