//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_Tatarincev_BPC2001
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единицы.
    /// </summary>
    public enum Единицы
    {
        
        [Caption("Гр")]
        1,
        
        [Caption("Л")]
        2,
        
        [Caption("Шт")]
        3,
        
        [Caption("Мл")]
        4,
    }
}
