//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_Tatarincev_BPC2001
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплаты.
    /// </summary>
    public enum ТипОплаты
    {
        
        [Caption("Безналичный")]
        1,
        
        [Caption("Наличный")]
        2,
        
        [Caption("За счет заведения")]
        3,
        
        [Caption("СБП")]
        4,
    }
}
